<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTotalPitchViewsByUser($user)
    {
        $qb = $this->createQueryBuilder('u');

        $qb
            ->select('SUM(p.views)')
            ->where('u.id = :id')
            ->setParameter('id', $user->getId())
            ->join('u.pitches', 'p');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
