pitches:
    type: rest
    resource: "@APIBundle/Controller/PitchesController.php"

comments:
    type: rest
    resource: "@APIBundle/Controller/CommentsController.php"

categories:
    type: rest
    resource: "@APIBundle/Controller/CategoriesController.php"

users:
    type: rest
    resource: "@APIBundle/Controller/UsersController.php"
