<?php

namespace PitchBundle\Repository;

/**
 * PitchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PitchRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMorePitchs($user, $pitch)
    {
        $qb = $this->createQueryBuilder('p');

        $qb->where('p.user = :user')
            ->andWhere('p != :pitch')
            ->setParameter('user', $user)
            ->setParameter('pitch', $pitch)
            ->orderBy('p.createdAt', 'desc')
            ->setMaxResults(4);

        return $qb->getQuery()->getResult();
    }
}
